language: rust
cache:
  - cargo
rust: 
  - 1.31.0
  - stable
  - nightly

env:
  - RUST_BACKTRACE=1

before_script:
  - set -e

script:
  - cargo check --verbose
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose

before_deploy:
  - echo '<head><meta http-equiv="refresh" content="0; URL=iec/index.html" /></head>' > target/doc/index.html

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    local-dir: target/doc
    on:
      branch: master
      # nightly gives nice inter-crate docs
      rust: nightly

notifications:
  email:
    on_success: never
